### ISSUE TITLE
Open Ownership

### ISSUE THREAD

**Issue by tute** [osscommunity/starters#8]
Aidan presented me with the idea of Open Ownership: when a contributor surpasses a given threshold of activity, they earn automatic commit rights. The active community members shape the community, as it happens in Wikimedia and StackOverflow. Also, it lowers the risk of stagnation for a project that loses interest, say, in a company, and would be effectively abandoned. @afeld, do you have more resources on this?

A Software solution would be ideal, as the whole point of Open Ownership is not to depend on people to gain commit rights. To get it started in a lean manner, though, we could add a section to project's READMEs that defines the criteria for gaining commit access. Something like (numbers need to be defined):

``` markdown
# Becoming a team member

You will get automatic commit access to the project when you:

* get accepted 5 patches in a month, and
* actively participate in 3 issues per week
```

Do you know of any community that works this way? What do you think?

**Comment by andrew** [comment]
Although I don't have any specific rules for my OSS projects, I offer commit access to someone as soon as they've made a couple of useful contributions. 

One other thing I'd tried to do, which I have little-to-no data to back up, is move projects that start to get some traction from my personal github account into an org so that the project feels more shared, rather than you're contributing to a project that someone else will get the benefit from.

When you have an org you can also use different levels of commit-bit, first giving the contributor team access and then admin access once they've reached a certain level of contributions.

It also helps with the bus-factor a little, things like travis permissions work so much better when the repo belongs to an org for example as multiple people can manage it.

**Comment by tute** [comment]
Closing in favor of new thread.
